# Generated by Django 3.1.6 on 2021-03-31 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='advertiser',
            fields=[
                ('adverid', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ADVERID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('role', models.CharField(max_length=25)),
                ('emailid', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'advertisertbl',
            },
        ),
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('emailid', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=10000)),
            ],
            options={
                'db_table': 'contactustbl',
            },
        ),
        migrations.CreateModel(
            name='publiser',
            fields=[
                ('pubid', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='PUBID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('cname', models.CharField(max_length=50)),
                ('addres1', models.CharField(max_length=100)),
                ('addres2', models.CharField(max_length=100)),
                ('emailid', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'publisertbl',
            },
        ),
        migrations.CreateModel(
            name='SavLoc',
            fields=[
                ('locid', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='LOCID')),
                ('pubid', models.IntegerField()),
                ('locimage', models.FileField(upload_to='')),
                ('locname', models.CharField(max_length=100)),
                ('locaddress', models.CharField(max_length=150)),
                ('pcname', models.CharField(max_length=50)),
                ('contactno', models.BigIntegerField()),
                ('parea', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('adtype', models.CharField(choices=[('Banner', 'Banner'), ('Bus Stand', 'Bus Stand'), ('Electric Poll', 'Electric Poll')], max_length=20)),
                ('noadv', models.IntegerField()),
                ('advsize', models.CharField(max_length=25)),
                ('advprice', models.IntegerField()),
            ],
            options={
                'db_table': 'addloctiontbl',
            },
        ),
    ]
