# Generated by Django 3.1.6 on 2021-04-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADPublicize', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='advRequest',
            fields=[
                ('advrequestid', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ADVREQUESTID')),
                ('locaddress', models.CharField(max_length=500)),
                ('parea', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('adtype', models.CharField(max_length=100)),
                ('advsize', models.CharField(max_length=50)),
                ('advprice', models.IntegerField()),
                ('pubid', models.IntegerField()),
                ('locid', models.IntegerField()),
                ('adverid', models.IntegerField()),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('cname', models.CharField(max_length=500)),
                ('contactno', models.BigIntegerField()),
                ('starttime', models.DateField()),
                ('lastdate', models.DateField()),
            ],
            options={
                'db_table': 'advrequesttbl',
            },
        ),
    ]
